### ISSUE TITLE
'API error 400: {"error":"Invalid URL: No URL specified"}

### ISSUE THREAD

**Issue by ravenreaving** [entrecore/php-gtmetrix#5]
i think this is a valid issue now.

here is the whole error

Warning: Missing argument 1 for Entrecore\GTMetrixClient\GTMetrixClient::startTest(), called in C:\xampp\htdocs\composer\index.php on line 13 and defined in C:\xampp\htdocs\composer\vendor\entrecore\gtmetrix\src\GTMetrixClient.php on line 196

Notice: Undefined variable: url in C:\xampp\htdocs\composer\vendor\entrecore\gtmetrix\src\GTMetrixClient.php on line 199

Fatal error: Uncaught exception 'Entrecore\GTMetrixClient\GTMetrixException' with message 'API error 400: {"error":"Invalid URL: No URL specified"} ' in C:\xampp\htdocs\composer\vendor\entrecore\gtmetrix\src\GTMetrixClient.php:112 Stack trace: #0 C:\xampp\htdocs\composer\vendor\entrecore\gtmetrix\src\GTMetrixClient.php(213): Entrecore\GTMetrixClient\GTMetrixClient->apiCall('/test', Array) #1 C:\xampp\htdocs\composer\index.php(13): Entrecore\GTMetrixClient\GTMetrixClient->startTest() #2 {main} thrown in C:\xampp\htdocs\composer\vendor\entrecore\gtmetrix\src\GTMetrixClient.php on line 112

![image](https://cloud.githubusercontent.com/assets/23471638/22173778/87614a74-df81-11e6-84f7-f58852b42052.png)

**Comment by ghost** [comment]
This is a documentation issue, you need to pass the full URL you want to test to the `startTest()` method. See the updated readme.

**Comment by ravenreaving** [comment]
I followed your documentation update.
now another error appeared.

Fatal error: Class 'GTMetrixTest' not found in C:\xampp\htdocs\composer\index.php on line 16

![image](https://cloud.githubusercontent.com/assets/23471638/22202305/5d07fd58-e11c-11e6-8a97-86913efde4a0.png)

By the way this is my code.
![asdasdasd](https://cloud.githubusercontent.com/assets/23471638/22202427/f889d562-e11c-11e6-86de-23f18a1dfd76.png)

**Comment by ghost** [comment]
Add this line after require:

`use Entrecore\GTMetrixClient\GTMetrixTest;`

Anyway, I would heavily recommend installing a proper IDE (like PHPStorm) instead of Notepad++ because that will help you discover issues with your code.

**Comment by ravenreaving** [comment]
hey janoszen thumbs up for your patience with me. hehe thankyou. i can take it from here now. thanks again. and for your recommendation ill downloaded it. but i will study first how to use it thankyou again.

**Comment by PetiteFlamme31** [comment]
Hello,

I already have some problems to do the same things.

I think the problem is due to the "tree" (sorry for my bad english, like "./folder/floder/...")..

Here is my code that is in a page for test a site (this page is in a public folder where there are all page for the web site: 
`<?php

use Entrecore\GTMetrixClient\GTMetrixClient;
use Entrecore\GTMetrixClient\GTMetrixTest;

require('../vendor/autoload.php');

$client = new GTMetrixClient();
$client->setUsername('x@x');
$client->setAPIKey('x');

$client->getLocations();
$client->getBrowsers();
$test = $client->startTest('x');

//Wait for result
while ($test->getState() != GTMetrixTest::STATE_COMPLETED &&
 $test->getState() != GTMetrixTest::STATE_ERROR) {
    $client->getTestStatus($test);
    sleep(5);
}
?>`

And here is the tree : 
https://www.catupload.com/download/8805c38a1da26cad8057d64ccfa45890.html

If you can help me, it would be very kind of you 👍 !
Thanks you.

**Comment by philcook** [comment]
@PetiteFlamme31 if this is still an issue please put it on my repo as I have taken over this project [philcook/php-gtmetrix](https://github.com/philcook/php-gtmetrix)

**Comment by PetiteFlamme31** [comment]
Hi,

Thank you very much for answers me today, and thank you for the time you spent !

Happy to see that you have updated the autoloader :).

I will test this tonight.

Thank you again, I wish you all the best with your work.

Have à nice evening !

Goodbye


De : Phil Cook
Envoyé : vendredi 25 mai à 17:40
Objet : Re: [entrecloud/php-gtmetrix] 'API error 400: {"error":"Invalid URL: No URL specified"} (#5)
À : entrecloud/php-gtmetrix
Cc : PetiteFlamme31, Mention


@PetiteFlamme31<https://github.com/PetiteFlamme31> if this is still an issue please put it on my repo as I have taken over this project philcook/php-gtmetrix<https://github.com/philcook/php-gtmetrix>
